// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-levels.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
function anonSupabase() {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY;
  return createClient(url, key, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-levels.ts
var list_levels_default = defineTool({
  name: "list_levels",
  title: "List levels",
  description: "List the physics levels available on Physics HQ (e.g. IGCSE, AS LEVEL, A2 LEVEL) together with how many past papers, topic-wise MCQ practice sets, topic-wise theory questions, and study materials exist for each level.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = anonSupabase();
    const [papers, mcq, theory, materials] = await Promise.all([
      supabase.from("papers").select("level"),
      supabase.from("topicwise_mcq_papers").select("level"),
      supabase.from("topicwise_theory_questions").select("level"),
      supabase.from("study_materials").select("level")
    ]);
    const err = papers.error || mcq.error || theory.error || materials.error;
    if (err) {
      return { content: [{ type: "text", text: err.message }], isError: true };
    }
    const levels = /* @__PURE__ */ new Map();
    const bump = (row, key) => {
      const entry = levels.get(row.level) ?? { papers: 0, topic_mcq: 0, topic_theory: 0, materials: 0 };
      entry[key] += 1;
      levels.set(row.level, entry);
    };
    papers.data?.forEach((r) => bump(r, "papers"));
    mcq.data?.forEach((r) => bump(r, "topic_mcq"));
    theory.data?.forEach((r) => bump(r, "topic_theory"));
    materials.data?.forEach((r) => bump(r, "materials"));
    const result = Array.from(levels.entries()).map(([level, counts]) => ({ level, ...counts })).sort((a, b) => a.level.localeCompare(b.level));
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: { levels: result }
    };
  }
});

// src/lib/mcp/tools/list-papers.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";
var list_papers_default = defineTool2({
  name: "list_papers",
  title: "List past papers",
  description: "List Cambridge past-paper MCQ practice papers on Physics HQ. Filter by level (IGCSE, AS LEVEL, A2 LEVEL), paper code, session (e.g. May/June, October/November), or year. Returns paper metadata and a URL to the PDF question paper.",
  inputSchema: {
    level: z.string().optional().describe("Filter by level, e.g. 'IGCSE', 'AS LEVEL', 'A2 LEVEL'."),
    paper_code: z.string().optional().describe("Filter by Cambridge paper code (e.g. '9702/12')."),
    session: z.string().optional().describe("Filter by exam session (e.g. 'May/June')."),
    year: z.number().int().optional().describe("Filter by year (e.g. 2023)."),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ level, paper_code, session, year, limit }) => {
    const supabase = anonSupabase();
    let q = supabase.from("papers").select("id, level, subject, paper_code, session, year, pdf_url").order("year", { ascending: false }).order("session", { ascending: true }).limit(limit ?? 50);
    if (level) q = q.eq("level", level);
    if (paper_code) q = q.eq("paper_code", paper_code);
    if (session) q = q.eq("session", session);
    if (typeof year === "number") q = q.eq("year", year);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { papers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-topic-mcq.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_topic_mcq_default = defineTool3({
  name: "list_topic_mcq_practice",
  title: "List topic-wise MCQ practice",
  description: "List topic-wise MCQ practice papers on Physics HQ. Each entry is a set of multiple-choice questions on a single physics topic, with a PDF and a suggested timer. Optionally filter by level or topic substring.",
  inputSchema: {
    level: z2.string().optional().describe("Filter by level (e.g. 'AS LEVEL')."),
    topic: z2.string().optional().describe("Case-insensitive substring match on topic (e.g. 'kinematics')."),
    limit: z2.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ level, topic, limit }) => {
    const supabase = anonSupabase();
    let q = supabase.from("topicwise_mcq_papers").select("id, level, topic, total_questions, timer_minutes, pdf_url").order("level", { ascending: true }).order("topic", { ascending: true }).limit(limit ?? 50);
    if (level) q = q.eq("level", level);
    if (topic) q = q.ilike("topic", `%${topic}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { papers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-topic-theory.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_topic_theory_default = defineTool4({
  name: "list_topic_theory_questions",
  title: "List topic-wise theory questions",
  description: "List topic-wise theory (structured) question sets on Physics HQ. Each entry has a question PDF and a matching answer-key PDF. Optionally filter by level or topic substring.",
  inputSchema: {
    level: z3.string().optional().describe("Filter by level (e.g. 'A2 LEVEL')."),
    topic: z3.string().optional().describe("Case-insensitive substring match on topic."),
    limit: z3.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ level, topic, limit }) => {
    const supabase = anonSupabase();
    let q = supabase.from("topicwise_theory_questions").select("id, level, topic, question_pdf_url, answer_pdf_url").order("level", { ascending: true }).order("topic", { ascending: true }).limit(limit ?? 50);
    if (level) q = q.eq("level", level);
    if (topic) q = q.ilike("topic", `%${topic}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { questions: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-study-materials.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^3.25.76";
var list_study_materials_default = defineTool5({
  name: "list_study_materials",
  title: "List study materials",
  description: "List study materials (notes, revision resources) on Physics HQ. Filter by level, subject, or folder path. Each entry links to a file URL (often a Google Drive document).",
  inputSchema: {
    level: z4.string().optional().describe("Filter by level (e.g. 'IGCSE')."),
    subject: z4.string().optional().describe("Filter by subject."),
    folder_path: z4.string().optional().describe("Filter by exact folder path."),
    search: z4.string().optional().describe("Case-insensitive substring match on title."),
    limit: z4.number().int().min(1).max(200).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ level, subject, folder_path, search, limit }) => {
    const supabase = anonSupabase();
    let q = supabase.from("study_materials").select("id, level, subject, title, description, file_type, file_url, folder_path").order("level", { ascending: true }).order("title", { ascending: true }).limit(limit ?? 50);
    if (level) q = q.eq("level", level);
    if (subject) q = q.eq("subject", subject);
    if (folder_path) q = q.eq("folder_path", folder_path);
    if (search) q = q.ilike("title", `%${search}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { materials: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "physics-hq-mcp",
  title: "Physics HQ",
  version: "0.1.0",
  instructions: "Read-only tools for Physics HQ, a Cambridge physics practice site by PRADAAP KUMAR. Use `list_levels` to see which levels (IGCSE, AS LEVEL, A2 LEVEL) are available and how much content each has. Use `list_papers` for full past-paper MCQs, `list_topic_mcq_practice` for topic-focused MCQ sets, `list_topic_theory_questions` for topic-focused structured questions (with answer keys), and `list_study_materials` for notes and revision resources. All tools return public content only.",
  tools: [list_levels_default, list_papers_default, list_topic_mcq_default, list_topic_theory_default, list_study_materials_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
